name: Create Pre-Release
on:
  workflow_dispatch:
jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4
      - name: Run tests
        run: echo "No tests configured yet"

  pre-release:
    needs: test
    name: Pre-Release
    uses: keptn/gh-automation/.github/workflows/pre-release-integration.yml@main

  release-assets:
    name: Release Assets
    needs: pre-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4
      - name: Add release assets
        env:
          RELEASE_TAG: ${{ needs.pre-release.outputs.RELEASE_TAG }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload "$RELEASE_TAG" ./LICENSE
