name: Create Release
on:
  workflow_dispatch:
jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.0.0
      - name: Run tests
        run: echo "No tests configured yet"

  release:
    needs: test
    name: Release
    uses: keptn/gh-automation/.github/workflows/release-integration.yml@v1.6.0

  release-assets:
    name: Release Assets
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.0.0
      - name: Add release assets
        env:
          RELEASE_TAG: ${{ needs.release.outputs.RELEASE_TAG }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload "$RELEASE_TAG" ./LICENSE
